# KNN

*Import Dependencies :*

In [22]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

*Load dataset :*

In [23]:
iris = load_iris()
X = iris.data
y = iris.target

xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2)

*Training classifier :*

In [24]:
clf = KNeighborsClassifier(n_neighbors=5).fit(xtrain, ytrain)

*Making predictions :*

In [25]:
ypred = clf.predict(xtest)

*Metrics :*

In [26]:
print("Accuracy: ", accuracy_score(ytest, ypred))
print(classification_report(ytest, ypred, target_names=iris.target_names))
print(confusion_matrix(ytest, ypred))

Accuracy:  0.8666666666666667
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       0.71      1.00      0.83        10
   virginica       1.00      0.60      0.75        10

    accuracy                           0.87        30
   macro avg       0.90      0.87      0.86        30
weighted avg       0.90      0.87      0.86        30

[[10  0  0]
 [ 0 10  0]
 [ 0  4  6]]
