# Cats vs Dogs

In [1]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
import os
import numpy as np
import cv2

2024-06-12 15:50:57.619080: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-12 15:50:57.619351: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-12 15:50:57.621190: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-12 15:50:57.649237: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-12 15:50:58.172899: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF

In [2]:
dPath = '../datasets/PetImages'
classes = ['Cat','Dog']

data = []
label = []

for i in classes:
    subdPath = f'{dPath}/{i}'
    paths = os.listdir(subdPath)
    for imgName in paths:
        img = cv2.imread(f'{subdPath}/{imgName}',0)
        img = cv2.resize(img,(256,256))
        data.append(img)
        if i == 'Cat' : label.append([1,0])
        else: label.append([0,1])

In [3]:
data = np.array(data)
label = np.array(label)

In [4]:
xTrain, xTest, yTrain, yTest = train_test_split(data,label,test_size=0.2,random_state=42)

In [5]:
l0 = tf.keras.layers.Dense(8,input_shape=(256,256))
fl = tf.keras.layers.Flatten()
l1 = tf.keras.layers.Dense(4,activation='relu')
l2 = tf.keras.layers.Dense(2,activation='softmax')
model = tf.keras.Sequential([l0,fl,l1,l2])

/home/ailab/anaconda3/envs/ai043_ml/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 256, 8)         │         2,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │         8,196 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │            10 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,262 (40.09 KB)

 Trainable params: 10,262 (40.09 KB)

 Non-trainable params: 0 (0.00 B)

In [7]:
model.compile(optimizer='adam',loss= tf.keras.losses.BinaryCrossentropy)

In [8]:
model.fit(xTrain,yTrain,batch_size=8,epochs=5,shuffle=True)

Epoch 1/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 54.0056  
Epoch 2/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 42.0424 
Epoch 3/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.0009 
Epoch 4/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.7490 
Epoch 5/5
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0519 


In [9]:
model.predict(xTest)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step


array([[0.50199574, 0.4980043 ],
       [0.50199574, 0.4980043 ],
       [0.50199574, 0.4980043 ],
       [0.60633016, 0.39366987]], dtype=float32)

In [10]:
yTest

array([[1, 0],
       [0, 1],
       [0, 1],
       [1, 0]])

In [11]:
dataTest = []
subdPath = f'{dPath}/test'

paths = os.listdir(subdPath)

for imgName in paths:
    img = cv2.imread(f'{subdPath}/{imgName}',0)
    img = cv2.resize(img,(256,256))
    dataTest.append(img)

In [12]:
dataTest = np.array(dataTest)

In [13]:
model.predict(dataTest)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[0.50199574, 0.4980043 ],
       [0.50199574, 0.4980043 ],
       [0.50199574, 0.4980043 ]], dtype=float32)