**Import dependencies :**

In [2]:
import os
import numpy as np
import keras
from keras import layers
from tensorflow import data as tf_data
import matplotlib.pyplot as plt

2024-06-12 14:38:43.522565: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-12 14:38:43.522839: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-12 14:38:43.524777: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-12 14:38:43.565471: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-12 14:38:44.093514: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF

**Import datasets :**

In [4]:
dPath = "../datasets/PetImages"

image_size = (180, 180)
batch_size = 128

train_ds, val_ds = keras.utils.image_dataset_from_directory(
    dPath,
    validation_split=0.2,
    subset="both",
    seed=42,
    image_size=image_size,
    batch_size=batch_size,
)

Found 20 files belonging to 2 classes.
Using 16 files for training.
Using 4 files for validation.


**Calculate LBP :**

In [4]:
from skimage import feature
import numpy as np
from tqdm import tqdm
class LocalBinaryPatterns:
    def __init__(self, numPoints, radius):
        # store the number of points and radius
        self.numPoints = numPoints
        self.radius = radius

    def describe(self, image, eps=1e-7):

        lbp = feature.local_binary_pattern(image, self.numPoints,
            self.radius, method="uniform")
        (hist, _) = np.histogram(lbp.ravel(),
            bins=np.arange(0, self.numPoints + 3),
            range=(0, self.numPoints + 2))
 
        hist = hist.astype("float")
        hist /= (hist.sum() + eps)
 
        return hist

In [10]:
from imutils import paths
import argparse
import cv2
import matplotlib.pyplot as plt
import os

In [11]:
desc = LocalBinaryPatterns(24, 8)
data = []
labels = []

In [12]:
for imagePath in paths.list_images(os.getcwd()):
    print(imagePath)
    imagePath=imagePath.split("/")[-2:]
    path=os.path.join(os.path.join(os.getcwd(),imagePath[0])+"/",imagePath[1])
    image = cv2.imread(path)
    print(path)
    plt.imshow(plt.imread(path))
    plt.show()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    hist = desc.describe(gray)
    labels.append(imagePath[-2])
    print(labels)
    data.append(hist)

/home/ailab/ai043_ml/datasets/PetImages/Cat/9938.jpg
/home/ailab/ai043_ml/Cat/9938.jpg


[ WARN:0@160.506] global loadsave.cpp:248 findDecoder imread_('/home/ailab/ai043_ml/Cat/9938.jpg'): can't open/read file: check file path/integrity


FileNotFoundError: [Errno 2] No such file or directory: '/home/ailab/ai043_ml/Cat/9938.jpg'

In [16]:
image_size = (180, 180)
batch_size = 128

train_ds, val_ds = keras.utils.image_dataset_from_directory(
    dPath,
    validation_split=0.2,
    subset="both",
    seed=1337,
    image_size=image_size,
    batch_size=batch_size,
    label_mode="binary"
)

Found 23410 files belonging to 2 classes.
Using 18728 files for training.
Using 4682 files for validation.


In [ ]:
knn = KNeighborsClassifier(n_neighbors=7) 
  
knn.fit(X_train, y_train) 
  
# Predict on dataset which model has not seen before 
print(knn.predict(X_test)) 

In [15]:
for i in train_ds:
    print(i)

(<tf.Tensor: shape=(128, 180, 180, 3), dtype=float32, numpy=
array([[[[121.63013  , 137.63013  , 124.63013  ],
         [120.37778  , 136.37778  , 123.37778  ],
         [121.82222  , 137.82222  , 124.82222  ],
         ...,
         [255.       , 255.       , 240.72096  ],
         [253.89035  , 255.       , 236.53775  ],
         [253.81111  , 254.81111  , 238.81111  ]],

        [[117.701485 , 133.70148  , 120.701485 ],
         [115.566666 , 131.56667  , 118.566666 ],
         [115.566666 , 131.56667  , 118.566666 ],
         ...,
         [255.       , 255.       , 242.43333  ],
         [254.4711   , 255.       , 241.80002  ],
         [254.43333  , 254.8237   , 242.90964  ]],

        [[120.36667  , 136.36667  , 123.36667  ],
         [116.98889  , 132.98889  , 119.98889  ],
         [116.05556  , 132.05556  , 119.05556  ],
         ...,
         [255.       , 255.       , 244.11115  ],
         [255.       , 255.       , 245.15556  ],
         [255.       , 254.05556  , 249.111

Corrupt JPEG data: 2226 extraneous bytes before marker 0xd9


(<tf.Tensor: shape=(128, 180, 180, 3), dtype=float32, numpy=
array([[[[133.48148   , 112.481476  ,  85.481476  ],
         [136.02777   , 115.02778   ,  88.02778   ],
         [141.44444   , 120.44444   ,  93.44444   ],
         ...,
         [108.44446   ,  90.44446   ,  66.44446   ],
         [105.90282   ,  88.23613   ,  63.569504  ],
         [104.083336  ,  87.083336  ,  61.083332  ]],

        [[135.625     , 114.625     ,  87.625     ],
         [137.95833   , 116.958336  ,  89.958336  ],
         [142.23611   , 121.23611   ,  94.23611   ],
         ...,
         [109.722244  ,  91.722244  ,  67.722244  ],
         [106.875046  ,  89.20836   ,  64.54173   ],
         [105.30557   ,  88.30557   ,  62.305573  ]],

        [[139.41667   , 118.416664  ,  91.416664  ],
         [140.375     , 119.375     ,  92.375     ],
         [143.83797   , 122.83796   ,  95.83796   ],
         ...,
         [111.152794  ,  93.152794  ,  69.152794  ],
         [109.18059   ,  91.5139    ,  66.847

Corrupt JPEG data: 228 extraneous bytes before marker 0xd9


(<tf.Tensor: shape=(128, 180, 180, 3), dtype=float32, numpy=
array([[[[117.20833  , 105.20833  ,  83.20833  ],
         [122.236115 , 110.56944  ,  90.90278  ],
         [125.43055  , 114.43055  ,  96.43055  ],
         ...,
         [166.52779  , 148.52779  , 124.527794 ],
         [166.23616  , 145.90285  , 122.90279  ],
         [163.43059  , 142.43059  , 121.43058  ]],

        [[121.02778  , 108.02778  ,  89.02778  ],
         [126.25     , 114.583336 ,  94.916664 ],
         [129.48611  , 118.48611  , 100.48611  ],
         ...,
         [169.44446  , 151.44446  , 127.44446  ],
         [168.5      , 149.50006  , 126.50001  ],
         [166.51392  , 145.51392  , 125.62506  ]],

        [[124.375    , 111.375    ,  92.375    ],
         [129.23611  , 117.56944  ,  99.236115 ],
         [132.59721  , 121.59722  , 103.59722  ],
         ...,
         [170.15279  , 152.15279  , 128.15279  ],
         [169.37495  , 150.37502  , 129.37495  ],
         [168.88892  , 147.88892  , 130.824

Corrupt JPEG data: 128 extraneous bytes before marker 0xd9
Corrupt JPEG data: 65 extraneous bytes before marker 0xd9


(<tf.Tensor: shape=(128, 180, 180, 3), dtype=float32, numpy=
array([[[[ 82.518524,  77.518524,  73.518524],
         [ 85.25    ,  80.25    ,  76.25    ],
         [ 87.25463 ,  84.25463 ,  79.25463 ],
         ...,
         [ 48.046295,  46.046295,  47.046295],
         [ 45.110992,  44.110992,  42.110992],
         [ 48.481495,  47.481495,  43.481495]],

        [[ 81.375   ,  76.375   ,  72.375   ],
         [ 79.      ,  74.      ,  70.      ],
         [ 86.541664,  83.541664,  78.541664],
         ...,
         [ 49.277756,  47.277756,  48.277756],
         [ 49.41668 ,  48.      ,  47.25004 ],
         [ 49.625   ,  48.625   ,  44.625   ]],

        [[ 79.84259 ,  74.84259 ,  70.84259 ],
         [ 78.04167 ,  73.04167 ,  69.04167 ],
         [ 85.38426 ,  82.38426 ,  77.38426 ],
         ...,
         [ 46.60649 ,  44.60649 ,  45.60649 ],
         [ 49.236095,  47.56941 ,  47.56947 ],
         [ 50.0324  ,  49.0324  ,  47.0324  ]],

        ...,

        [[ 37.291656,  40.29165

Corrupt JPEG data: 396 extraneous bytes before marker 0xd9


(<tf.Tensor: shape=(128, 180, 180, 3), dtype=float32, numpy=
array([[[[ 14.       ,  15.       ,   9.       ],
         [ 14.       ,  15.       ,   9.       ],
         [ 14.       ,  15.       ,   9.       ],
         ...,
         [ 12.       ,  13.       ,   7.       ],
         [ 12.       ,  13.       ,   7.333313 ],
         [ 12.       ,  13.       ,   8.       ]],

        [[ 14.       ,  15.       ,   9.       ],
         [ 14.       ,  15.       ,   9.       ],
         [ 14.       ,  15.       ,   9.       ],
         ...,
         [ 12.       ,  13.       ,   7.       ],
         [ 12.       ,  13.       ,   7.333313 ],
         [ 12.       ,  13.       ,   8.       ]],

        [[ 14.       ,  15.       ,   9.       ],
         [ 14.       ,  15.       ,   9.       ],
         [ 14.       ,  15.       ,   9.       ],
         ...,
         [ 12.       ,  13.       ,   7.       ],
         [ 12.       ,  13.       ,   7.333313 ],
         [ 12.       ,  13.       ,   8.   

Corrupt JPEG data: 239 extraneous bytes before marker 0xd9


(<tf.Tensor: shape=(128, 180, 180, 3), dtype=float32, numpy=
array([[[[  5.4675927,  10.467593 ,  16.467592 ],
         [  6.3472223,  10.347222 ,  19.347221 ],
         [ 12.990739 ,  17.435183 ,  25.10185  ],
         ...,
         [ 56.416504 ,  47.25909  ,  36.282253 ],
         [ 33.43053  ,  25.180489 ,  13.388843 ],
         [ 41.08792  ,  34.171253 ,  21.712921 ]],

        [[  6.555556 ,  11.555555 ,  14.930555 ],
         [  7.666667 ,  12.666667 ,  17.416668 ],
         [  7.4305544,  12.430554 ,  18.430555 ],
         ...,
         [ 40.13878  ,  39.01378  ,  36.027695 ],
         [ 13.791649 ,  11.958275 ,   7.7083206],
         [ 27.138763 ,  26.638763 ,  20.888763 ]],

        [[  9.537036 ,  15.537037 ,  14.12037  ],
         [  7.416666 ,  12.652778 ,  15.138888 ],
         [ 15.944441 ,  20.94444  ,  26.94444  ],
         ...,
         [ 38.564747 ,  40.98141  ,  47.236046 ],
         [  4.1109324,   5.819222 ,   9.388736 ],
         [ 21.319336 ,  24.736004 ,  24.995

2024-05-21 16:23:38.603036: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
